// Post list
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAILURE = 'FETCH_ACTIVITIES_FAILURE';
export const RESET_ACTIVITIES = 'RESET_ACTIVITIES';


// Validate post fields like Title, Categries on the server
export const VALIDATE_ACTIVITIES_FIELDS = 'VALIDATE_ACTIVITIES_FIELDS';
export const VALIDATE_ACTIVITIES_FIELDS_SUCCESS = 'VALIDATE_ACTIVITIES_FIELDS_SUCCESS';
export const VALIDATE_ACTIVITIES_FIELDS_FAILURE = 'VALIDATE_ACTIVITIES_FIELDS_FAILURE';
export const RESET_ACTIVITIES_FIELDS = 'RESET_ACTIVITIES_FIELDS';

// Fetch post
export const FETCH_ACTIVITY = 'FETCH_ACTIVITY';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAILURE = 'FETCH_ACTIVITY_FAILURE';
export const RESET_ACTIVE_ACTIVITY = 'RESET_ACTIVE_ACTIVITY';

//Create new post
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';
export const CREATE_ACTIVITY_FAILURE = 'CREATE_ACTIVITY_FAILURE';
export const RESET_NEW_ACTIVITY = 'RESET_NEW_ACTIVITY';


// search types!
export const BEGIN_SEARCH = 'BEGIN_SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
