// change email
export const ADMIN_GET_DATA = 'ADMIN_GET_DATA';
export const ADMIN_GET_DATA_SUCCESS = 'ADMIN_GET_DATA_SUCCESS';
export const ADMIN_GET_DATA_FAILURE = 'ADMIN_GET_DATA_FAILURE';

// provider for approval
export const ADMIN_PROVIDERS_FOR_APPROVAL = 'ADMIN_PROVIDERS_FOR_APPROVAL';
export const ADMIN_PROVIDERS_FOR_APPROVAL_SUCCESS = 'ADMIN_PROVIDERS_FOR_APPROVAL_SUCCESS';
export const ADMIN_PROVIDERS_FOR_APPROVAL_FAILURE = 'ADMIN_PROVIDERS_FOR_APPROVAL_FAILURE';


// change email actions
export const ADMIN_CHANGE_EMAIL = 'ADMIN_CHANGE_EMAIL';
export const ADMIN_CHANGE_EMAIL_SUCCESS = 'ADMIN_CHANGE_EMAIL_SUCCESS';
export const ADMIN_CHANGE_EMAIL_FAILURE = 'ADMIN_CHANGE_EMAIL_FAILURE';


//aprove or reject an provider
export const APROVE_REJECT_PROVIDER = 'APROVE_REJECT_PROVIDER';
export const APROVE_REJECT_PROVIDER_SUCCESS = 'APROVE_REJECT_PROVIDER_SUCCESS';
export const APROVE_REJECT_PROVIDER_FAILURE = 'APROVE_REJECT_PROVIDER_FAILURE';
