export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';


// SIGNUP_USER
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';

// SIGNUP_PROVIDER
// actions to be created
export const SIGNUP_PROVIDER = 'SIGNUP_PROVIDER';
export const SIGNUP_SUCCESS_PROVIDER = 'SIGNUP_SUCCESS_PROVIDER';
export const SIGNUP_ERROR_PROVIDER = 'SIGNUP_ERROR_PROVIDER';

//  LOGIN (BOTH for user and provider)
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN = 'MANUAL_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// LOGOUT (BOTH for user and provider)
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
