// Credits
export const GET_CREDITS = 'GET_CREDITS';
export const GET_CREDITS_SUCCESS = 'GET_CREDITS_SUCCESS';
export const GET_CREDITS_FAILURE = 'GET_CREDITS_FAILURE';

export const ADD_CREDITS = 'ADD_CREDITS';
export const ADD_CREDITS_SUCCESS = 'ADD_CREDITS_SUCCESS';
export const ADD_CREDITS_FAILURE = 'ADD_CREDITS_FAILURE';

// change profile
export const PARENT_CHANGE_PROFILE = 'PARENT_CHANGE_PROFILE';
export const PARENT_CHANGE_PROFILE_SUCCESS = 'PARENT_CHANGE_PROFILE_SUCCESS';
export const PARENT_CHANGE_PROFILE_FAILURE = 'PARENT_CHANGE_PROFILE_FAILURE'

// change credentials
export const PARENT_CHANGE_CREDENTIALS = 'PARENT_CHANGE_CREDENTIALS';
export const PARENT_CHANGE_CREDENTIALS_SUCCESS = 'PARENT_CHANGE_CREDENTIALS_SUCCESS';
export const PARENT_CHANGE_CREDENTIALS_FAILURE = 'PARENT_CHANGE_CREDENTIALS_FAILURE'
