// change profile
export const PROVIDER_CHANGE_PROFILE = 'PROVIDER_CHANGE_PROFILE';
export const PROVIDER_CHANGE_PROFILE_SUCCESS = 'PROVIDER_CHANGE_PROFILE_SUCCESS';
export const PROVIDER_CHANGE_PROFILE_FAILURE = 'PROVIDER_CHANGE_PROFILE_FAILURE'

// change credentials
export const PROVIDER_CHANGE_CREDENTIALS = 'PROVIDER_CHANGE_CREDENTIALS';
export const PROVIDER_CHANGE_CREDENTIALS_SUCCESS = 'PROVIDER_CHANGE_CREDENTIALS_SUCCESS';
export const PROVIDER_CHANGE_CREDENTIALS_FAILURE = 'PROVIDER_CHANGE_CREDENTIALS_FAILURE'
