// change profile
export const PROVIDER_CHANGE_PROFILE = 'PROVIDER_CHANGE_PROFILE';
export const PROVIDER_CHANGE_PROFILE_SUCCESS = 'PROVIDER_CHANGE_PROFILE_SUCCESS';
export const PROVIDER_CHANGE_PROFILE_FAILURE = 'PROVIDER_CHANGE_PROFILE_FAILURE'

// change credentials
export const PROVIDER_CHANGE_CREDENTIALS = 'PROVIDER_CHANGE_CREDENTIALS';
export const PROVIDER_CHANGE_CREDENTIALS_SUCCESS = 'PROVIDER_CHANGE_CREDENTIALS_SUCCESS';
export const PROVIDER_CHANGE_CREDENTIALS_FAILURE = 'PROVIDER_CHANGE_CREDENTIALS_FAILURE'


// Data
export const PROVIDER_GET_DATA = 'PROVIDER_GET_DATA';
export const PROVIDER_GET_DATA_SUCCESS = 'PROVIDER_GET_DATA_SUCCESS';
export const PROVIDER_GET_DATA_FAILURE = 'PROVIDER_GET_DATA_FAILURE';

//Provider Activities
export const PROVIDER_GET_ACTIVITIES = 'PROVIDER_GET_ACTIVITIES';
export const PROVIDER_GET_ACTIVITIES_SUCCESS = 'PROVIDER_GET_ACTIVITIES_SUCCESS';
export const PROVIDER_GET_ACTIVITIES_FAILURE = 'PROVIDER_GET_ACTIVITIES_FAILURE';
