export const BUY_TICKET = 'BUY_TICKET';
export const BUY_TICKET_SUCCESS = 'BUY_TICKET_SUCCESS';
export const BUY_TICKET_FAILURE = 'BUY_TICKET_FAILURE';

export const GET_TICKET_PDF = 'GET_TICKET_PDF';
export const GET_TICKET_PDF_SUCCESS = 'GET_TICKET_PDF_SUCCESS';
export const GET_TICKET_PDF_FAILURE = 'GET_TICKET_PDF_FAILURE';
