// SIGNUP_USER
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';

// SIGNUP_PROVIDER
// actions to be created
export const SIGNUP_PROVIDER = 'SIGNUP_PROVIDER';
export const SIGNUP_SUCCESS_PROVIDER = 'SIGNUP_SUCCESS_PROVIDER';
export const SIGNUP_ERROR_PROVIDER = 'SIGNUP_ERROR_PROVIDER';

//  LOGIN (BOTH for user and provider)
export const MANUAL_LOGIN = 'MANUAL_LOGIN';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_SUCCESS_PROVIDER = 'LOGIN_SUCCESS_PROVIDER';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// login action type for username. So we can easily update UI
export const LOGIN_SUCCESS_USER_USERNAME = 'LOGIN_SUCCESS_USER_USERNAME';
export const LOGIN_SUCCESS_PROVIDER_USERNAME = 'LOGIN_SUCCESS_PROVIDER_USERNAME';
export const LOGOUT_SUCCESS_UNSET_USERNAME = 'LOGOUT_SUCCESS_UNSET_USERNAME';

// LOGOUT (BOTH for user and provider)
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

// FORGOT
export const FORGOT = 'FORGOT';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_ERROR = 'FORGOT_ERROR';


// administrator
export const LOGIN_SUCCESS_ADMINISTRATOR_USERNAME = 'LOGIN_SUCCESS_ADMINISTRATOR_USERNAME';
export const LOGIN_SUCCESS_ADMINISTRATOR = 'LOGIN_SUCCESS_ADMINISTRATOR';
